name: Semantic Versioning
on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semantic Release

        run: |
          npm install -g semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Semantic Release
        run: |
          semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}